version: "3.9"

services:
  identity.api:
    build:
      context: .
      dockerfile: Services/IdentityService/IdentityService.WebAPI/Dockerfile
  advertisement.api:
    build:
      context: .
      dockerfile: Services/Advertisement/Advertisement.WebAPI/Dockerfile
  cars-catalog.api:
    build:
      context: .
      dockerfile: Services/CarsCatalog/CarsCatalog.WebAPI/Dockerfile
  chat.api:
    build:
      context: .
      dockerfile: Services/Chat/Chat.WebAPI/Dockerfile
  
  postgres:
    image: postgres:latest
    
  mongodb:
    image: mongo:latest
    
  redis:
    image: redis:latest

  elasticsearch:
    image: elasticsearch:8.10.2
        
  kibana:
    image: kibana:8.10.2

  rabbitmq:
    image: rabbitmq:management